# Use an official Python runtime as the base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Install pipenv for dependency management
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install Python dependencies system-wide
RUN pipenv install --deploy --system

# Copy the application files and training script
COPY scripts/app.py ./app.py
COPY scripts/XgBoost.py ./XgBoost.py
COPY data/apple_quality.csv ./apple_quality.csv
# Train the model to create the pickle file
RUN python XgBoost.py

# Expose the Flask port
EXPOSE 5000

# Run the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]